trigger: none

pr: none

resources:
  pipelines:
  - pipeline: build
    source: terraform-ci

stages:

- stage: Plan
  displayName: 'Terraform Plan'

  jobs:
  - job: PlanJob
    displayName: 'Generate Terraform Plan'

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: 'devopstest'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init -backend-config=backend.conf
          terraform validate
          terraform plan -var-file="dev.cfg"

- stage: Apply
  displayName: 'Terraform Apply'
  dependsOn: Plan

  jobs:
  - deployment: ApplyDeployment
    displayName: 'Apply Terraform'

    environment: Dev

    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: AzureCLI@2
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: 'devopstest'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
               pwd
               ls -la
               terraform init -backend-config=backend.conf
               terraform apply -var-file="dev.cfg" -auto-approve